name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Increase swap space
      run: |
        sudo fallocate -l 4G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5
        pip install buildozer cython virtualenv
        
    - name: Configure Buildozer
      run: |
        buildozer init
        echo -e "[app]\ntitle = MyApp\npackage.name = myapp\npackage.domain = org.example\nrequirements = python3,flet\nandroid.permissions = INTERNET\nandroid.api = 33\nandroid.sdk_path = /usr/lib/android-sdk\nandroid.accept_sdk_license = True" > buildozer.spec
        
    - name: Build APK
      run: |
        buildozer -v android debug
        ls -la bin/
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: flet-app
        path: bin/*.apk
